version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - eureka-network

  soft-ioc:
    build:
      context: ./iocs
      dockerfile: Dockerfile
    ports:
      - "5064:5064"
    volumes:
      - ./iocs:/app
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge 